name: tugaskelompok
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^13.0.4
  url_launcher: ^6.3.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  http: ^1.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
